config/routes.rb
Fbcomments::Application.routes.draw do

  resources :groups do
    resources :posts
  end
  

   root :to => "home#login"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Facebooker2::Rails::Controller

  protect_from_forgery
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    elsif current_facebook_user and @current_user.nil?
      @current_user = User.find_by_facebook_id(current_facebook_user.id)
    end
  end
  
  helper_method :current_user
  
  
  def login_required
    if current_user.nil?
      flash[:notice] = "You must login to access this page"
      session[:return_to] = request.request_uri
      redirect_to :controller =>'home', :action =>'login' and return
    end
  end
  
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :login_required

  def index 
    #get current users groups
    @groups = current_facebook_user.groups
	
	#determine selected user group or get first group id if default group is not selected
	@default_group = @current_user.default_group
	@default_group = @groups.first.id if @default_group.nil? && @groups.first != nil
  end

  def default
	render :json => { :result => @current_user.update_attributes(:default_group => params['id'] == 'nil' ? nil : params['id']) }
  end

  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   
  def login
  end

  def create
    @user = User.find_by_email(params[:email])
    create_via_facebook_connect if @user.nil?

    if @user != nil 
      session[:user_id] = @user.id
      redirect_to session[:return_to]||url_for(groups_path)
      session[:return_to]=nil
    else
      flash[:error] = "Unable to log you in"
      render :action=>"login"
    end
  end

  def create_via_facebook_connect
    if current_facebook_user 
      #look for an existing user
      @user = User.find_by_facebook_id(current_facebook_user.id)	  
      if @user.nil?
        #if one isn't found - fetch user data via Mogli lib and create new user
        current_facebook_user.fetch
	    @user = User.new(:name => current_facebook_user[:name], :email => current_facebook_user[:email], :facebook_id => current_facebook_user[:id], :facebook_session_key => current_facebook_client.access_token)
		@user.save
      end
    end
  end

  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :login_required

  def index    
    @group = Mogli::Group.new({:id=>params['group_id']}, current_facebook_client)
	@group.fetch
	@posts = @group.feed
	render :layout => false
  end
  
  def new
    @group = Mogli::Group.new({:id=>params['group_id']}, current_facebook_client)
	@group.fetch
  end

  def create
    puts params.inspect
	
    @group = Mogli::Group.new({:id=>params['group_id']}, current_facebook_client)
	@group.fetch
	#@posts = @group.feed

    #flash[:notice] = "Note sent to #{note.recipient.email}"
    if current_facebook_user
	  puts current_facebook_client.class.post(current_facebook_client.api_path(@group.id + '/feed'),
			:query=>current_facebook_client.default_params.merge(
			           {:name => "#{current_facebook_user.name} Post a message using app!",
                        :link=>'http://staging.operations.engineyard.com/groups',
                        :message=>params['message']})).inspect
    end
    redirect_to groups_path	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/index.html.erb
<% content_for (:javascript) do %>
$(document).ready(function() {
  $('#group').bind('change', function() {
	$('#posts_container').load('/groups/' + $(this).val() + '/posts',  function() {
	  FB.XFBML.parse(document.getElementById('posts_container'));
	});
  });

  $('#posts_container').load('/groups/<%=@default_group%>/posts',  function() {
    FB.XFBML.parse(document.getElementById('posts_container'));
  });
  
  $('#def_group').bind('change', function() {
	var group_id = $(this).is(':checked') ? $('#group').val() : 'nil'
	$.post('/groups/default/' + group_id ,  function() {
	  alert ('Default group was saved');
	});
  });
 
 

  });  
<% end %>
<br/>
<select name="group" id="group" >
<% @groups.each do |group| %>
 <option value="<%=group.id%>" <%= 'selected' if @default_group == group.id %>><%=group.name%></option>
<% end %>
</select>
<br/>
<input id="def_group" name="def_group" type="checkbox" selected="false" /> Default group <br/>
<div id="posts_container" >Posts</div>

app/views/home/index.html.erb
<select name="current_page" >
<% @groups.each do |group| %>
 <option value="<%=group.id%>" ><%=group.name%></option>
<% end %>
</select>

<br/>
<input type="checkbox" selected="false" /> Default group <br/>

<% @posts.each do |post| %>
 <%=post.message%><br/> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Group Hug | Sponsored by Engine Yard</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script> 
  <%= yield (:javascript) %>
  </script>
</head>
<body>
	
  	<div id="content">
		<div id="logo">
				<h1><a href="#">Group Hug</a></h1>
				&nbsp;sponsored by <a href="http://engineyard.com">Engine Yard</a>
						<p class="status">
						<% if current_facebook_user !=nil %>
							<%= fb_logout_link("Logout", request.url) %><br />
							<% else
							# you must explicitly request permissions for facebook user fields
							# here we instruct facebook to ask the user for permission for our website
							# to access the user's facebook email and birthday, groups,read_stream
							%>
							<%= fb_login_and_redirect( url_for(:action => 'create', :controller => 'home', :only_path => false),:perms => 'email,user_birthday,user_groups,read_stream, publish_stream') %>
							<% end %>
						</p>
		</div>
		<br/>
		<div id="left">
		<%= "Welcome #{@current_user.name}!"  if @current_user !=nil %>
		<br/>
		<%= yield %>
		</div>
	</div>	

  <%= fb_connect_async_js %>



</body>
</html>

app/views/posts/create.html.erb
<h3>Message was posted</h3>

app/views/posts/index.html.erb
<%= link_to "Post Message", url_for(new_group_post_path(@group.id)) %>
<br>
<table>
	<tbody>
<% @posts.each do |post| %>
<%#=post.from.inspect%>
	<tr>
  		<td>
    		<fb:profile-pic uid="<%=post.from.id%>" linked="false" size="q"></fb:profile-pic>
  		</td>
  		<td width="600">
    <%=post.message%><br/> 
    <%= time_ago_in_words(post.updated_time) %> ago
  		</td>
	</tr>
<% end %>
</table>
<br/><br/>

app/views/posts/new.html.erb
<h1>Post a wall message to: <%= @group.name %></h1>

<% form_tag  url_for(group_posts_path(@group.id)), :method=>:post do -%>
 
  
  <%= hidden_field_tag 'group_id', @group.id %>
  
  <div class="field">
    <%= text_area_tag 'message', nil, :rows => 10, :cols => 60 %>
  </div>
  <div class="field">
    <%= check_box_tag 'send_via_email', 'yes', true %> Send the whole group an email
  </div>
  <div class="actions">
    <%= submit_tag 'Save' %>
  </div>
<% end -%>
 
<%= link_to 'Back', url_for(groups_path) %>